

```{r}
link="https://raw.githubusercontent.com/bjcrawley/finalproject543/master/543%20Data%20-%20Final%20Data.csv"
MergeData = read.csv(file=url(link), header = TRUE, stringsAsFactors = FALSE)

```

```{r}
str(MergeData)
```

```{r}
#repeat the code below for every column that you want to be numeric#
MergeData$Population= as.numeric(gsub(",","",MergeData$Population))
MergeData$Development = as.factor(MergeData$Development)
MergeData$Pop.Density= as.factor(MergeData$Pop.Density)
MergeData$Density= as.numeric(gsub(",","",MergeData$Density))
MergeData$Emissions= as.numeric(gsub(",","",MergeData$Emissions))
MergeData$Continent= as.factor(MergeData$Continent)
```
```{r}
summary(MergeData$Population)
```

```{r}
MergeData$DensityCUT=cut(MergeData$Density,
                      breaks = c(2.0,34.5,83.0,203.0,8358.0),
                      labels = c("Low", "Medium", "High", "Very High"),
                      ordered_result = T)
```

```{r}
MergeData$EmissionsCUT=cut(MergeData$Emissions,
                      breaks = c(0, 0.7, 2.7, 6.4, 38.2),
                      labels = c("Low", "Medium", "High", "Very High"),
                      ordered_result = T)
```

```{r}
#size categories:
#Large= greather than 100 million
#Medium= between 100 million and 50 million
#Small= between 50 million and 25 million
#Tiny= less than 25 million
MergeData$PopulationCUT=cut(MergeData$Population,
                          breaks = c(18090,25000000,50000000,100000000,1439000000),
                          labels = c("Tiny","Small","Medium", "Large"),
                          ordered_result = T)
(CatOfPopDev=table(MergeData$PopulationCUT,MergeData$Development))
```

```{r}
(PopDevCol=prop.table(CatOfPopDev,
                      margin = 2))
```

```{r}
CatofPopDev_DF= as.data.frame(CatOfPopDev)
names(CatofPopDev_DF)= c("Population", "Development", "Frequency")
CatofPopDev_DF$pctCol= as.data.frame(PopDevCol)[,3]
head(CatofPopDev_DF)
```

```{r}
str(CatofPopDev_DF)
```

```{r}
CatofPopDev_DF$Population=factor(CatofPopDev_DF$Population,
                                 levels = c("Tiny","Small","Medium", "Large"),ordered = T)
#
CatofPopDev_DF$Development=factor(CatofPopDev_DF$Development,
                                 levels = c('Low','Medium','High','Very High'),ordered = T)

```



```{r}
# CatofPopDev_DF$Development = as.character(CatofPopDev_DF$Development)
# #Changing the aweful names to something readable!
# CatofPopDev_DF$Development[as.character(CatofPopDev_DF$Development) == "HIGHHUMANDEVELOPMENT"] <- "High Development"
# CatofPopDev_DF$Development[CatofPopDev_DF$Development == "LOWHUMANDEVELOPMENT"] <- "Low Development"
# CatofPopDev_DF$Development[CatofPopDev_DF$Development == "VERYHIGHHUMANDEVELOPMENT"] <- "Very High Development"
# CatofPopDev_DF$Development[CatofPopDev_DF$Development == "MEDIUMHUMANDEVELOPMENT"] <- "Medium Development"
```


```{r}
#Arithmetic

MergeData[,c(3,5,12)]=lapply(MergeData[,c(3,5,12)],scale)

MergeData$Index=apply(MergeData[,c(3,5,12)],
                       MARGIN = 1, # by row / 2 by column
                       median)
```


```{r}
MergeData$Population.2020.=MergeData$Population/1000000
```

##you also need:
```{r}
MergeData$Development=factor(MergeData$Development,
                             levels = c('Low','Medium','High','Very High'),
                             ordered = T)
```



```{r}
mapLink="https://raw.githubusercontent.com/bjcrawley/finalproject543/master/Countries_WGS84.json"
```

```{r}
library(geojsonio)
PROJmap="+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
wazipMap=topojson_read(mapLink,crs=PROJmap,stringsAsFactors = FALSE)
```

```{r}
library(lwgeom)
wazipMap=st_make_valid(wazipMap) #making valid

```

```{r}
library(ggplot2)
ggplot(data=wazipMap) + geom_sf()
```

```{r}
names(wazipMap)
```

```{r}
str(wazipMap$CNTRY_NAME)
```

```{r}
layerContrib=merge(wazipMap,MergeData, 
                   by.x='CNTRY_NAME', 
                   by.y='Country',
                   all.x=F)
```

```{r}
# This will make just a border of the state
library(rmapshaper)
baseMap <- ms_dissolve(wazipMap) #dissolve creates a basemap, with just the border 
```

```{r}
ggplot(baseMap) + geom_sf()
```

```{r}
library(RColorBrewer)
library(tmap)
```

```{r}
numberOfClasses = 5
colorForScale='YlGnBu' # color scale
```

```{r}
layerContrib$POP20cut=cut_number(layerContrib$Population.2020.,numberOfClasses,
                            ordered_result=T, #ordered variable
                            dig.lab=5) #5 digits
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer1 = baseLayer + geom_sf(data = layerContrib, aes(fill=POP20cut),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Population")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer1   
```

```{r}
base = ggplot(MergeData, aes(x=HDI,y=Emissions)) 
plot1= base +  geom_point() + geom_smooth(method=lm, linetype="dashed", color="darkred", fill="blue") +theme_minimal()
plot1
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer2 = baseLayer + geom_sf(data = layerContrib, aes(fill=DensityCUT),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Population Density")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer2 
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer3 = baseLayer + geom_sf(data = layerContrib, aes(fill=EmissionsCUT),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Emissions")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer3 
```

```{r}


baseLayer=ggplot(data = baseMap) +geom_sf() 
layer4 = baseLayer + geom_sf(data = layerContrib, aes(fill=Development),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Development")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer4 
```

```{r}
library(ggpubr)
ggarrange(layer3, layer4,ncol = 1) # to plot multiple plots 
```

```{r}
numberOfClasses = 4
colorForScale='YlGnBu' # color scale
```

```{r}
layerContrib$IndexCUT=cut_number(layerContrib$Index,numberOfClasses,
                            ordered_result=T, #ordered variable
                            dig.lab=5) #5 digits
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer5 = baseLayer + geom_sf(data = layerContrib, aes(fill=IndexCUT),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Index")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer5 
```

