```{r}
link="https://raw.githubusercontent.com/bjcrawley/finalproject543/master/543%20Data%20-%20Final%20Data.csv"
MergeData = read.csv(file=url(link), header = TRUE, stringsAsFactors = FALSE)

#repeat the code below for every column that you want to be numeric#
MergeData$Population= as.numeric(gsub(",","",MergeData$Population))
MergeData$Development = as.factor(MergeData$Development)
MergeData$Pop.Density= as.factor(MergeData$Pop.Density)
MergeData$Density= as.numeric(gsub(",","",MergeData$Density))
MergeData$Emissions= as.numeric(gsub(",","",MergeData$Emissions))
MergeData$Continent= as.factor(MergeData$Continent)
class(MergeData$Development)
```

```{r}
#Arithmetic
MergeData$Index=apply(MergeData[,c(3,5,12)],
                       MARGIN = 1, # by row / 2 by column
                       median)
```

```{r}
str(MergeData)
```


```{r}
head(MergeData$Population)
```

```{r}
names(MergeData)
```

```{r}
summary(MergeData$Population)
```

```{r}
summary(MergeData$Density)
```

```{r}
MergeData$PopDens=cut(MergeData$Density,
                      breaks = c(2.0,34.5,83.0,203.0,8358.0),
                      labels = c("Low", "Medium", "High", "Very High"))
```

```{r}
summary(MergeData$Emissions)
```

```{r}
MergeData$CatEms=cut(MergeData$Emissions,
                      breaks = c(0, 0.7, 2.7, 6.4, 38.2),
                      labels = c("Low", "Medium", "High", "Very High"))
```


```{r}
#size categories:
#Large= greather than 100 million
#Medium= between 100 million and 50 million
#Small= between 50 million and 25 million
#Tiny= less than 25 million
MergeData$CatofPop=cut(MergeData$Population,
                          breaks = c(18090,25000000,50000000,100000000,1439000000),
                          labels = c("Tiny","Small","Medium", "Large"))

CatOfPopDev=table(MergeData$CatofPop,MergeData$Development)

#Marginal Percent Table
(PopDevCol=prop.table(CatOfPopDev,
                      margin = 2))
```


```{r}
CatofPopDev_DF= as.data.frame(CatOfPopDev)
names(CatofPopDev_DF)= c("Population", "Development", "Frequency")

CatofPopDev_DF$pctCol= as.data.frame(PopDevCol)[,3]
head(CatofPopDev_DF)
```

```{r}
#Found that Category was read in as a factor preventing me from changing the variable names the code below changes the column into characters. 
class(CatofPopDev_DF$Development)
```

```{r}
CatofPopDev_DF$Development = as.character(CatofPopDev_DF$Development)

#Changing the aweful names to something readable!
CatofPopDev_DF$Development[as.character(CatofPopDev_DF$Development) == "HIGHHUMANDEVELOPMENT"] <- "High Development"
CatofPopDev_DF$Development[CatofPopDev_DF$Development == "LOWHUMANDEVELOPMENT"] <- "Low Development"
CatofPopDev_DF$Development[CatofPopDev_DF$Development == "VERYHIGHHUMANDEVELOPMENT"] <- "Very High Development"
CatofPopDev_DF$Development[CatofPopDev_DF$Development == "MEDIUMHUMANDEVELOPMENT"] <- "Medium Development"
```

#### Elizabeth's Bar Plots

```{r}
library(ggplot2)
library(scales)
base = ggplot(data = CatofPopDev_DF, aes(x=Population, y=Development))
base1 = base + geom_point(aes(size = pctCol*100))
base2 = base1 + geom_text(aes(label = percent(pctCol)),
                                    nudge_x = 0.4,
                                    size=3)
base3 = base2 + theme_minimal()
base4 = base3 + theme(legend.position="none")
```

```{r}
#I want to reorder the graphs because they ar being displayed in alphabetical order instead of something like Very High, High, Medium, Low. This means that I have to turn the Development column into a factor and designate the order with levels. 
CatofPopDev_DF$Development = as.factor(CatofPopDev_DF$Development)
class(CatofPopDev_DF$Development)
```

```{r}
levels(CatofPopDev_DF$Development) =(c("Very High Development", "High Development", "Medium Development", "Low Development"))
```

```{r}
BarBase = ggplot(CatofPopDev_DF, aes(x=Population, y=Frequency, fill=Population))
BarBase1 = BarBase + geom_bar( stat = "identity" ) + theme_minimal()
BarBase2 = BarBase1 + facet_grid(~ Development)


BarBase3 = BarBase2 + theme(axis.text.x = element_blank(),
                            legend.position = "bottom",
                            axis.title.x = element_blank())


###

barTitle = "Does Size Matter?"
barSubtitle = "An Analysis of Countries' Human Development"
barCaption = "Source: Perkins et.al (2020)"
BarBase4 = BarBase3 + labs(title = barTitle, 
                           subtitle = barSubtitle,
                           caption = barCaption) +
  theme(plot.caption = element_text(hjust = 0), 
        plot.title = element_text(hjust = 0))

###

BarBase4
```

### Ben's Heat Map ###

```{r}
base = ggplot(CatofPopDev_DF,
              aes(x = Population,
                  y = reorder(Development, pctCol),
                  fill = pctCol*100))
heat = base + geom_tile()

heat = heat + scale_fill_gradient(low = "blue",
                                  high = "red")

heat = heat + theme_minimal()
heat = heat + labs(y="Development")
heat = heat + theme(axis.text.x = element_text(angle = 0,
                                               vjust = 0.6),
                    axis.text.y = element_text(size = 7),
                    legend.title = element_blank(),
                    legend.position="right",
                    legend.direction = "vertical",
                    legend.key.width = unit(1,"cm"),
                    legend.key.height = unit(1,"cm"),
                    axis.title.x = element_text(size = 10),
                    axis.title.y = element_blank())

barTitle = "Does Size Matter?"
barSubtitle = "An Analysis of Countries' Human Development"
barCaption = "Source: Perkins et.al (2020)"

heat = heat + labs(title = barTitle,
                   subtitle = barSubtitle,
                   caption = barCaption) + theme(plot.caption = element_text(hjust = 0), 
        plot.title = element_text(hjust = 0))

heat
```



### Cheng-Wei's Dot Plot ###

```{r}
base3 = ggplot(CatofPopDev_DF, aes(x=Population,y=Development))
# plot value as point, size by value of percent
tablePlot = base3 + geom_point(aes(size = pctCol*100)) 
# add value of Percent as label
tablePlot = tablePlot + geom_text(aes(label = percent(pctCol)),
                                    nudge_x = 0.4,
                                    size=3,color='red')
tablePlot = tablePlot + theme_minimal() # less ink
tablePlot = tablePlot + theme(legend.position="none") # no legend
tablePlot

```


#### SPATIAL TEST ####


```{r}
MergeData$Population.2020.=MergeData$Population/1000000
```


```{r, eval=TRUE}
mapLink="https://raw.githubusercontent.com/bjcrawley/finalproject543/master/Countries_WGS84.json"
```

```{r, eval=TRUE}
library(geojsonio)
PROJmap="+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
wazipMap=topojson_read(mapLink,crs=PROJmap,stringsAsFactors = FALSE)
```

```{r, eval=TRUE}
object.size(wazipMap)
```

```{r, eval=TRUE}
library(lwgeom)
wazipMap=st_make_valid(wazipMap) #making valid
```

```{r, eval=TRUE}
object.size(wazipMap)
```

```{r, eval=TRUE}
library(ggplot2)
ggplot(data=wazipMap) + geom_sf()
```

```{r}
names(wazipMap)
```

```{r}
str(wazipMap$CNTRY_NAME)
```

```{r}
layerContrib=merge(wazipMap,MergeData, 
                   by.x='CNTRY_NAME', 
                   by.y='Country',
                   all.x=F)
```

```{r}
# This will make just a border of the state
library(rmapshaper)
baseMap <- ms_dissolve(wazipMap) #dissolve creates a basemap, with just the border 
```

```{r}
ggplot(baseMap) + geom_sf()
```

```{r}
library(RColorBrewer)
library(tmap)
```

```{r}
numberOfClasses = 5

colorForScale='YlGnBu' # color scale

```

```{r}
layerContrib$cut=cut_number(layerContrib$Population.2020.,numberOfClasses,
                            ordered_result=T, #ordered variable
                            dig.lab=5) #5 digits
```




```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer1 = baseLayer + geom_sf(data = layerContrib, aes(fill=cut),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Population")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer1    
```

```{r}
base = ggplot(MergeData, aes(x=HDI,y=Emissions)) 
plot1= base +  geom_point() + geom_smooth(method=lm, linetype="dashed", color="darkred", fill="blue") +theme_minimal()
plot1
```





###Ben's Individual Work###






###More Mapping Work###

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer2 = baseLayer + geom_sf(data = layerContrib, aes(fill=PopDens),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Population Density")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer2 
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer3 = baseLayer + geom_sf(data = layerContrib, aes(fill=CatEms),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Emissions")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer3 
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer4 = baseLayer + geom_sf(data = layerContrib, aes(fill=Development),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Development")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer4 
```

```{r}
library(ggpubr)

ggarrange(layer3, layer4,ncol = 1) # to plot multiple plots 
```



### Index ###

```{r}
numberOfClasses = 4

colorForScale='YlGnBu' # color scale

```

```{r}
layerContrib$cut2=cut_number(layerContrib$Index,numberOfClasses,
                            ordered_result=T, #ordered variable
                            dig.lab=5) #5 digits
```

```{r}
baseLayer=ggplot(data = baseMap) +geom_sf() 
layer5 = baseLayer + geom_sf(data = layerContrib, aes(fill=cut2),color=NA,show.legend = T) +
                 scale_fill_brewer(palette = colorForScale,
                                   name = "Index")
#plots the baselayer with the newly created map ontop of it
#aes(fill=column or cut you want to)
layer5 
```




































