

```{r}
link="https://docs.google.com/spreadsheets/d/e/2PACX-1vQvh-fKdh4RVEFtYigc5Uk4_aTXncPVFyouTKsSO5T1KZMeDDKsj-F6ENYokFBNaYrFv_lEojDyVB-X/pub?output=csv"
MergeData = read.csv(file=url(link), header = TRUE, stringsAsFactors = FALSE)
MergeData$Population= as.numeric(gsub(",","",MergeData$Population))
MergeData$GDPperCapita= as.numeric(gsub(",","",MergeData$GDPperCapita))
MergeData$Electricity= as.numeric(gsub(",","",MergeData$Electricity))
```

```{r}
# After we loaded the data, we need to check the data type in each column.
# If the data type is not correct, then we need to change the data type before we try to do the data visualzation.  
```

```{r}
MergeData$CatofPop=cut(MergeData$Population,
                          breaks = c(53200,2900000,9900000,33000000,1439000000),
                          labels = c("Low","Medium","High", "Very High"))
MergeData$CatofPop= as.character(MergeData$CatofPop)
```

```{r}
# We try to make a category column by divided the population column into four groups
```


```{r}
library(ggplot2)
library(ggrepel)
base = ggplot(MergeData, aes(x=Population,y=Emissions,color=Continent)) 
plot1= base +  geom_point() +theme_minimal() + geom_text_repel(aes(label=ifelse(Emissions > 20 | Population > 330000000, Country, "")))
Titles=list(Ti="Relationship between Population and Emissions ?",
           Sou="Source: Worldometer2020")


plot1= plot1 + labs(title =Titles$Ti,caption = Titles$Sou)

plot1= plot1 + theme(plot.title=element_text(hjust=0),
                   plot.caption=element_text(hjust=0))+ theme(axis.title = element_blank())

plot1
```
```{r}
# We want to know the relationship between emissions and population. Therefore, we choose a scatter plot. In order to follow 'keep it simple' approach, so I use theme_minimal() to keep the background clear. After plotting, we found out that there's no obvious correlated between them. Therefore, we decided to do a boxplot. 
```

```{r}
# Only label the country which emissions and population is above 3rd Qu. 
```
```{r}
#From this scatter plot, we notice that all of the points gather in the left corner. Also, there are lots of outliers.
#In this case, it would be hard to tell whether emissions and population is correlated. Therefore, we would like to know will is be any difference if we choose to use the column category of the population instead of population.
```


```{r}
colorForScale='YlGnBu'
base30=ggplot(fill = CatofPop,data=MergeData[MergeData$Emissions>0.625 & MergeData$Emissions<=2.5,],
            aes(x=reorder(CatofPop,Emissions),y=Emissions))
box30=base30 + geom_boxplot() + labs(title="Higher the population higher Emissions?",subtitle = "Emissions v.s Category of Population",caption ="Source: World Bank, Worldometer2020")+ theme_minimal()
box30=box30+theme(plot.title=element_text(hjust=0),
                  #plot.sutitle=element_text(hjust=0),
                  plot.caption=element_text(hjust=0))+ theme(axis.title.x = element_blank())
box30=box30+theme(axis.text.x = element_text(angle = 45, hjust = 1,
                                   size = 10)) +scale_fill_brewer(palette =colorForScale)
box30
```

```{r}
# Also we reordered the column to make the graph more precise.
```
```{r}
#Before we saw the result from our plot, we always assume more people, more carbon dioxide emissions, vise versa. However, it might not always be the true.
#According to the plot, we can find that high population actually produce less CO2 than low population. How come? The explanation may be for those developed countries such as Europe. They might be good at energy saving. Therefore, they produce the lowest CO2 emissions. On the other hand, developing countries like India, since they have large amount of people, and they don’t know how to save the energy efficient, so they produce CO2 emissions the most. 
```


```{r}
colorForScale='YlGnBu'
base=ggplot(data = MergeData,
            aes( fill = Continent, x=as.factor(Continent),
                y=Emissions))
boxBycontinent=base + geom_boxplot()

boxBycontinent= boxBycontinent + theme(axis.text.x = element_text(angle = 45,
                                                          hjust = 1,
                                                          size = 10)) +scale_fill_brewer(palette =colorForScale)+ theme_minimal()
Titles=list(Ti="Which continent has the most CO2 emissions?",
           Sou="Source: Worldometer2020")

boxBycontinent= boxBycontinent + labs(title =Titles$Ti,caption = Titles$Sou)


boxBycontinent= boxBycontinent + theme(plot.title=element_text(hjust=0),
                   plot.caption=element_text(hjust=0)) + theme(axis.title = element_blank())




boxBycontinent
```

```{r}
# We label the continent and plot the univariate column: Emissions 
```
```{r}
#Apparently, Africa is the one which produce the least CO2 emissions. As for rest of them, we could see at Asia and Europe first, these two continent’s top 25 percent countries emit almost the same amount of carbon dioxide. However, when you take a closer look, the Asia’s median is weigh lower than Europe. This result shows that the amount of carbon dioxide emitted by Asian countries varies widely, while the European countries emit the same amount of carbon dioxide.
#For most of Americas countries, they do not emit huge amount of CO2 emission, however, just as Asia, the outliers are many times higher than standard deviation
```


